alias ls='ls -o --color --group-directories-first'
alias l='ls -o --color --group-directories-first'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias pacman='sudo pacman'


## Other tests to get colour
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}
