#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


# environment variables
export EDITOR=nano
export COLORTERM=xterm
export VISUAL=emacs

export PATH="$HOME/bin:$PATH"

# run archey on start up
# archey3

# customize your PS1
PS1='[\u@\h \W]\$ '
